
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxagunnjsvfmoqzavohx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4YWd1bm5qc3ZmbW9xemF2b2h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzQxMzQsImV4cCI6MjA2NTU1MDEzNH0.3URBru6X9cMw1J4xyJlJ8dZbS7Mc-_zcyyEFbEIqhbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true
  }
});
